language: go

go:
  - 1.13.x

env:
  global:
    - GO111MODULE=on

stages:
  - test
  - build
  - name: push
    if: fork = false

jobs:
  include:
    - stage: test
      script:
        - make travis-setup
        - make test
    - stage: build
      script:
        - make travis-setup
        - export TAG=$(git rev-parse --short $TRAVIS_COMMIT)
        - make docker-build IMG=quay.io/slrz/synapse-operator:$TAG
    - stage: push
      script:
        - make travis-setup
        - export TAG=$(git rev-parse --short $TRAVIS_COMMIT)
        - docker login --password "$QUAY_PASSWORD" --username "$QUAY_USERNAME" quay.io
        - make docker-build docker-push IMG=quay.io/slrz/synapse-operator:$TAG
