# permissions for end users to view synapsis.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: synapse-viewer-role
rules:
- apiGroups:
  - matrix.slrz.net
  resources:
  - synapsis
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - matrix.slrz.net
  resources:
  - synapsis/status
  verbs:
  - get
